### PR TITLE
Store

### PR DESCRIPTION
**Pull request by theSherwood**

### CODE REVIEW

**Comment by greggirwin** [comment]
@x8x same question as for the other PR. :^)

**Comment by greggirwin** [comment]
Heeeyyy Adam,

Touching base to see how you're doing...and we had a couple questions
you might know the answer to, like, do we still need Node running for
localhost testing (Maarten wanted to know). Aside from a couple little
things, and a new small showstopper or two, we're ready to call the
DiaGrammar release a Go. Thanks so much for the part you played in
helping us get here.

-- 
Best regards,
 Gregg                            mailto:gregg@red-lang.org

**Comment by theSherwood** [comment]
Hi @greggirwin,

That's a good question. The dev docker setup is using volumes rather than copying over the data into the container. So you can do either in theory (running node locally or within the container). However, the current docker dev image does not have node in it. So that would need to be changed if you want to run the node commands from within docker. Hopefully that makes sense.

Also, thanks for the opportunity to work on this and sorry for just falling off the map. Things have gotten pretty crazy on my end. Hopefully, I'll be back to the Red community sometime in late 2021.

Best regards,

Adam

**Comment by greggirwin** [comment]
Thanks Adam. We'll be happy to see you again when you have time, and
have slept. :^)

-- 
Best regards,
 Gregg                            mailto:gregg@red-lang.org

**Comment by greggirwin** [comment]
Hey Adam,

Redlake needs a W-9 filled out, for your contracting work this year.

-- 
Best regards,
 Gregg                            mailto:gregg@red-lang.org

**Pull request merged**
